name: Restart signaling server

on:
  workflow_run:
    workflows: [Signaling server]
    types: [completed]

permissions:
  actions: write

env:
  GH_TOKEN: ${{ github.token }}
  
jobs:
  call-workflow:
    runs-on: ubuntu-latest
    environment: Signalling Server

    steps:
      - uses: actions/checkout@v4
      - uses: sersoft-gmbh/setup-gh-cli-action@v1.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Dispatch workflow using GitHub CLI
        if: ${{ github.event.workflow_run.conclusion != 'success' && vars.ENABLE_AUTO_RESTART == 'true' }}
        run: |
          gh workflow run signaling-server.yml --ref main
